---
title: Koren.mk
description: Lorem ipsum dolorem
url: 
baseurl: 
lang: en
permalink: "/:title/"

website: courses # options: blog | courses | publications

google_analytics: 

paginate: 4
paginate_path: "/blog/:num/" 

markdown: kramdown
highlighter: rouge

plugins:
- jekyll-seo-tag
- jekyll-paginate

exclude:
- vendor
- ".bundle"
- ".sass-cache"
- config
- Gemfile
- Gemfile.lock
- node_modules
- log
- tmp
- Rakefile
- package.json
- CHANGELOG
- LICENSE
- README
- "/docs"

livereload: true

collections:
  publications:
    output: true
    permalink: /:name
  courses:
    output: true
    permalink: /:name
  posts:
    output: false
    permalink: /:name
  software:
    output: false

# Defaults
defaults:
  - scope:
      path: ""
      type: publications
    values:
      layout: publication
  - scope:
      path: ""
      type: courses
    values:
      layout: course
  - scope:
      path: ""
      type: posts
    values:
      layout: post
