social:
  facebook: "#"
  twitter: "#"
  instagram: "#"
  linkedin: "#"
  google: "#"
  github: "#"

publications:
  logo: /assets/images/koren-mk.svg
  favicon: /assets/images/favicon/koren-mk/png/favicon-koren-mk
  copyright: "&copy; 2024 Coded Thinking OÜ"
  url: https://koren.mk
  plausible: koren.mk

courses:
  logo: /assets/images/koren-dev.svg
  favicon: /assets/images/favicon/koren-dev/png/favicon-koren-dev
  copyright: "&copy; 2024 Coded Thinking OÜ"
  url: https://koren.dev
  plausible: koren.dev

blog:
  logo: /assets/images/koren-ct.svg
  favicon: /assets/images/favicon/codedthinking/png/favicon-codedthinking
  copyright: "&copy; 2024 Coded Thinking OÜ"
  url: https://codedthinking.com
  plausible: codedthinking.com
